CREATE TABLE `variable` (
	`id`	INTEGER,
	`abbrev`	TEXT,
	`label`	TEXT,
	`name`	TEXT,
	`data_type`	TEXT,
	`not_null`	TEXT,
	`type`	TEXT,
	`status`	TEXT,
	`display_name`	TEXT,
	`ontology_reference`	TEXT,
	`property_id`	INTEGER,
	`method_id`	INTEGER,
	`scale_id`	INTEGER,
	`variable_set`	TEXT,
	`synonym`	TEXT,
	`description`	TEXT,
	`default_value`	TEXT,
	`data_level`	TEXT
);